name: homebrew-confluent-hub-client
lang: unknown
lang_version: unknown
git:
  enable: true
github:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_enable: false
  tasks:
    - name: release-client
      branch: master
      pipeline_file: tasks/release-client/task.yml
      parameters:
        - name: RELEASE_TAG
          required: true
          default_value: 'NONE'
          description: 'Tag which is used to build and upload an archive'
        - name: UPDATE_LATEST
          required: true
          default_value: 'False'
          description: 'Override latest archive(http://client.hub.confluent.io/confluent-hub-client-latest.tar.gz) with a current archive.'
          options:
            - 'True'
            - 'False'
