# This file is managed by ServiceBot plugin - Semaphore. The content in this file is created using a common
# template and configurations in service.yml.
# Modifications in this file will be overwritten by generated content in the nightly run.
# For more information, please refer to the page:
# https://confluentinc.atlassian.net/wiki/spaces/Foundations/pages/2871296194/Add+SemaphoreCI
apiVersion: v1alpha
kind: Project
metadata:
  name: homebrew-confluent-hub-client
  description: ""
spec:
  visibility: private
  repository:
    url: git@github.com:confluentinc/homebrew-confluent-hub-client.git
    run_on:
    - branches
    - tags
    - pull_requests
    pipeline_file: .semaphore/semaphore.yml
    integration_type: github_app
    status:
      pipeline_files:
      - path: .semaphore/semaphore.yml
        level: pipeline
    whitelist:
      branches:
      - master
      - main
      - /^v\d+\.\d+\.x$/
      - /^gh-readonly-queue.*/
  custom_permissions: true
  debug_permissions:
  - empty
  - default_branch
  - non_default_branch
  - pull_request
  - forked_pull_request
  - tag
  attach_permissions:
  - default_branch
  - non_default_branch
  - pull_request
  - forked_pull_request
  - tag
  tasks:
  - name: release-client
    scheduled: False
    branch: "master"
    pipeline_file: tasks/release-client/tas.yml
    parameters:
    - name: RELEASE_TAG
      required: True
      default_value: "NONE"
      description: "Tag which is used to build and upload an archive"
    - name: UPDATE_LATEST
      required: True
      default_value: "False"
      description: "Override latest archive(http://client.hub.confluent.io/confluent-hub-client-latest.tar.gz) with a current archive."
      options:
       - True
       - False
